[platformio]
default_envs = m5stack-cores3

[env:m5stack-cores3]
platform = espressif32@6.3.2
board = esp32s3box
framework = arduino
board_build.arduino.memory_type = qio_qspi
board_build.arduino.partitions = my_cores3_16MB.csv
board_build.f_flash = 80000000L
board_build.filesystem = spiffs
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
upload_speed = 1500000
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_M5STACK_CORES3
lib_deps =
    m5stack/M5Unified @ 0.2.15
