"""Validate the pinned 2M K1 dictionary and emit an aligned flash array."""
import argparse
import hashlib
from pathlib import Path
import struct

EXPECTED_SHA256 = "cd1ed65241600b29ced9fde627b1543d93f5f5c0cd5297a4dba42d3f01d8806a"


def validate(data):
    if len(data) < 8 or data[:4] != b"K1D1":
        raise ValueError("Expected K1D1 dictionary")
    version, count = struct.unpack_from("<HH", data, 4)
    if version != 2 or 8 + count * 16 > len(data):
        raise ValueError("Invalid dictionary version/section table")
    sections = {}
    spans = []
    for i in range(count):
        name, offset, size = struct.unpack_from("<8sII", data, 8 + i * 16)
        name = name.rstrip(b"\0").decode("ascii")
        if name in sections or offset % 4 or offset < 8 + count * 16 or offset + size > len(data):
            raise ValueError("Invalid dictionary section: " + name)
        sections[name] = data[offset:offset + size]
        spans.append((offset, offset + size))
    spans.sort()
    if any(a[1] > b[0] for a, b in zip(spans, spans[1:])):
        raise ValueError("Overlapping dictionary sections")
    required = {"louds", "counts", "surfck", "records", "pool", "classes", "keytab", "keyesc",
                "moratab", "chains", "matrixc", "charr", "unk", "poolck", "termck"}
    if not required.issubset(sections) or "matrix" in sections or "char" in sections:
        raise ValueError("Expected 2M matrixc/charr dictionary")
    if hashlib.sha256(data).hexdigest() != EXPECTED_SHA256:
        raise ValueError("Dictionary SHA-256 mismatch; obtain the documented 44000 dictionary")
    return data


def generate(blob, output):
    data = validate(Path(blob).read_bytes())
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="ascii", newline="\n") as f:
        f.write("/* Generated by dictionary_to_header.py; do not edit. */\n#include <stdint.h>\n")
        f.write("static const uint8_t saan_dict_blob[] __attribute__((aligned(16))) = {\n")
        for i in range(0, len(data), 24):
            f.write(",".join(str(b) for b in data[i:i+24]) + ",\n")
        f.write("};\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--blob", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    generate(args.blob, args.out)
